<a href="https://colab.research.google.com/github/rosh4nn/ML-IrisDataset-project1/blob/main/IrisData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('/content/IRIS.csv')
df.head()

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [ ]:
df.shape

(150, 5)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [ ]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [ ]:
df[df.duplicated()]

     sepal_length  sepal_width  petal_length  petal_width         species
34            4.9          3.1           1.5          0.1     Iris-setosa
37            4.9          3.1           1.5          0.1     Iris-setosa
142           5.8          2.7           5.1          1.9  Iris-virginica

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df[df.duplicated()]

Empty DataFrame
Columns: [sepal_length, sepal_width, petal_length, petal_width, species]
Index: []

In [ ]:
df.isna().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [ ]:
x = df.iloc[:,:-1]
x

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[147 rows x 4 columns]

In [ ]:
y = df.iloc[:,-1]
y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: species, Length: 147, dtype: object

In [ ]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1)

In [ ]:
x_train

     sepal_length  sepal_width  petal_length  petal_width
127           6.1          3.0           4.9          1.8
134           6.1          2.6           5.6          1.4
44            5.1          3.8           1.9          0.4
140           6.7          3.1           5.6          2.4
28            5.2          3.4           1.4          0.2
..            ...          ...           ...          ...
135           7.7          3.0           6.1          2.3
139           6.9          3.1           5.4          2.1
74            6.4          2.9           4.3          1.3
143           6.8          3.2           5.9          2.3
39            5.1          3.4           1.5          0.2

[117 rows x 4 columns]

In [ ]:
x_test

     sepal_length  sepal_width  petal_length  petal_width
101           5.8          2.7           5.1          1.9
95            5.7          3.0           4.2          1.2
56            6.3          3.3           4.7          1.6
105           7.6          3.0           6.6          2.1
100           6.3          3.3           6.0          2.5
77            6.7          3.0           5.0          1.7
91            6.1          3.0           4.6          1.4
55            5.7          2.8           4.5          1.3
46            5.1          3.8           1.6          0.2
61            5.9          3.0           4.2          1.5
5             5.4          3.9           1.7          0.4
16            5.4          3.9           1.3          0.4
93            5.0          2.3           3.3          1.0
14            5.8          4.0           1.2          0.2
60            5.0          2.0           3.5          1.0
33            5.5          4.2           1.4          0.2
75            6.6          3.0           4.4          1.4
29            4.7          3.2           1.6          0.2
68            6.2          2.2           4.5          1.5
36            5.5          3.5           1.3          0.2
119           6.0          2.2           5.0          1.5
86            6.7          3.1           4.7          1.5
31            5.4          3.4           1.5          0.4
130           7.4          2.8           6.1          1.9
111           6.4          2.7           5.3          1.9
19            5.1          3.8           1.5          0.3
53            5.5          2.3           4.0          1.3
50            7.0          3.2           4.7          1.4
122           7.7          2.8           6.7          2.0
144           6.7          3.3           5.7          2.5

In [ ]:
y_train

127     Iris-virginica
134     Iris-virginica
44         Iris-setosa
140     Iris-virginica
28         Iris-setosa
            ...
135     Iris-virginica
139     Iris-virginica
74     Iris-versicolor
143     Iris-virginica
39         Iris-setosa
Name: species, Length: 117, dtype: object

In [ ]:
y_test

101     Iris-virginica
95     Iris-versicolor
56     Iris-versicolor
105     Iris-virginica
100     Iris-virginica
77     Iris-versicolor
91     Iris-versicolor
55     Iris-versicolor
46         Iris-setosa
61     Iris-versicolor
5          Iris-setosa
16         Iris-setosa
93     Iris-versicolor
14         Iris-setosa
60     Iris-versicolor
33         Iris-setosa
75     Iris-versicolor
29         Iris-setosa
68     Iris-versicolor
36         Iris-setosa
119     Iris-virginica
86     Iris-versicolor
31         Iris-setosa
130     Iris-virginica
111     Iris-virginica
19         Iris-setosa
53     Iris-versicolor
50     Iris-versicolor
122     Iris-virginica
144     Iris-virginica
Name: species, dtype: object

In [ ]:
y_train.value_counts()

species
Iris-virginica     41
Iris-setosa        39
Iris-versicolor    37
Name: count, dtype: int64

In [ ]:
from imblearn.over_sampling import SMOTE

smote = SMOTE()
x_train1,y_train1 = smote.fit_resample(x_train,y_train)

In [ ]:
y_train1.value_counts()

species
Iris-virginica     41
Iris-setosa        41
Iris-versicolor    41
Name: count, dtype: int64

In [ ]:
# feature Scaling Using StandardScaler

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
x_train1 = sc.fit_transform(x_train1)
x_train1

array([[ 3.62720003e-01, -1.13177013e-01,  6.68996930e-01,
         7.97624436e-01],
       [ 3.62720003e-01, -1.13257550e+00,  1.07101368e+00,
         2.70677454e-01],
       [-8.45774206e-01,  1.92561996e+00, -1.05393202e+00,
        -1.04669000e+00],
       [ 1.08781653e+00,  1.41672609e-01,  1.07101368e+00,
         1.58804491e+00],
       [-7.24924785e-01,  9.06221475e-01, -1.34108684e+00,
        -1.31016349e+00],
       [-1.69172015e+00,  3.96522231e-01, -1.39851781e+00,
        -1.31016349e+00],
       [ 1.81291305e+00, -3.68026635e-01,  1.47303044e+00,
         7.97624436e-01],
       [ 1.32951537e+00,  3.96522231e-01,  1.12844465e+00,
         1.45630816e+00],
       [-8.45774206e-01,  1.16107110e+00, -1.34108684e+00,
        -1.17842675e+00],
       [-1.20677681e-01, -1.38742512e+00,  7.26427895e-01,
         1.06109793e+00],
       [-3.62376523e-01, -1.64227474e+00,  3.72563157e-02,
        -1.24532783e-01],
       [ 3.62720003e-01, -6.22876257e-01,  1.52118246e-01,
         1.38940708e-01],
       [ 1.20866595e+00, -6.22876257e-01,  6.11565965e-01,
         2.70677454e-01],
       [-1.20677681e-01,  1.92561996e+00, -1.16879395e+00,
        -1.17842675e+00],
       [-9.66623627e-01,  1.41592072e+00, -1.34108684e+00,
        -1.31016349e+00],
       [-1.45002131e+00,  3.96522231e-01, -1.34108684e+00,
        -1.31016349e+00],
       [ 9.66967107e-01, -3.68026635e-01,  4.96704035e-01,
         1.38940708e-01],
       [-1.57087073e+00, -1.89712437e+00, -1.39851781e+00,
        -1.17842675e+00],
       [-1.69172015e+00, -1.13177013e-01, -1.39851781e+00,
        -1.31016349e+00],
       [ 8.46117686e-01, -1.13177013e-01,  1.01358272e+00,
         7.97624436e-01],
       [ 2.41870582e-01, -1.13177013e-01,  6.11565965e-01,
         7.97624436e-01],
       [-1.08747305e+00, -1.38742512e+00,  4.39273070e-01,
         6.65887691e-01],
       [ 1.69206363e+00,  3.96522231e-01,  1.30073754e+00,
         7.97624436e-01],
       [ 2.41870582e-01,  9.06221475e-01,  4.39273070e-01,
         5.34150945e-01],
       [ 1.08781653e+00,  6.51371853e-01,  1.12844465e+00,
         1.19283467e+00],
       [-2.41527102e-01, -6.22876257e-01,  6.68996930e-01,
         1.06109793e+00],
       [-2.41527102e-01, -8.77725879e-01,  2.66980175e-01,
         1.38940708e-01],
       [-1.20832247e+00,  9.06221475e-01, -1.22622491e+00,
        -1.31016349e+00],
       [ 4.83569424e-01,  9.06221475e-01,  9.56151755e-01,
         1.45630816e+00],
       [ 6.04418844e-01, -1.89712437e+00,  3.81842105e-01,
         1.38940708e-01],
       [-1.20832247e+00, -1.13177013e-01, -1.34108684e+00,
        -1.44190024e+00],
       [-1.32917189e+00,  3.96522231e-01, -1.39851781e+00,
        -1.31016349e+00],
       [ 4.83569424e-01, -3.68026635e-01,  3.24411140e-01,
         1.38940708e-01],
       [ 1.20866595e+00, -1.13177013e-01,  1.01358272e+00,
         1.19283467e+00],
       [ 7.25268265e-01,  1.41672609e-01,  1.01358272e+00,
         7.97624436e-01],
       [-1.45002131e+00,  9.06221475e-01, -1.34108684e+00,
        -1.17842675e+00],
       [ 4.83569424e-01, -6.22876257e-01,  6.11565965e-01,
         7.97624436e-01],
       [ 1.69206363e+00,  1.41592072e+00,  1.35816851e+00,
         1.71978166e+00],
       [ 1.71740112e-04, -8.77725879e-01,  2.09549210e-01,
        -2.56269528e-01],
       [-1.08747305e+00, -1.64227474e+00, -2.49898509e-01,
        -2.56269528e-01],
       [-1.20677681e-01, -1.13257550e+00, -1.35036579e-01,
        -2.56269528e-01],
       [ 1.57121421e+00, -1.13177013e-01,  1.24330658e+00,
         1.19283467e+00],
       [-6.04075364e-01,  1.67077034e+00, -1.28365588e+00,
        -1.31016349e+00],
       [-2.41527102e-01, -3.68026635e-01, -7.76056142e-02,
         1.38940708e-01],
       [ 7.25268265e-01,  3.96522231e-01,  8.98720790e-01,
         1.45630816e+00],
       [ 1.71740112e-04, -1.13257550e+00,  1.52118246e-01,
         7.20396281e-03],
       [-1.20677681e-01, -6.22876257e-01,  2.09549210e-01,
         1.38940708e-01],
       [ 6.04418844e-01, -6.22876257e-01,  7.83858860e-01,
         4.02414200e-01],
       [-4.83225943e-01,  1.67077034e+00, -1.28365588e+00,
        -1.31016349e+00],
       [-9.66623627e-01,  3.96522231e-01, -1.45594877e+00,
        -1.31016349e+00],
       [-7.24924785e-01,  2.69016883e+00, -1.28365588e+00,
        -1.44190024e+00],
       [ 6.04418844e-01, -8.77725879e-01,  6.68996930e-01,
         7.97624436e-01],
       [-9.66623627e-01,  1.16107110e+00, -1.39851781e+00,
        -1.17842675e+00],
       [ 8.46117686e-01,  3.96522231e-01,  7.83858860e-01,
         1.06109793e+00],
       [ 1.21021161e-01, -1.13177013e-01,  7.83858860e-01,
         7.97624436e-01],
       [-7.24924785e-01,  1.16107110e+00, -1.28365588e+00,
        -1.31016349e+00],
       [-8.45774206e-01,  6.51371853e-01, -1.16879395e+00,
        -9.14953256e-01],
       [-2.41527102e-01, -1.38742512e+00,  9.46872806e-02,
        -1.24532783e-01],
       [-1.08747305e+00,  1.41672609e-01, -1.28365588e+00,
        -1.44190024e+00],
       [ 1.69206363e+00, -1.13177013e-01,  1.18587561e+00,
         5.34150945e-01],
       [-1.20677681e-01, -3.68026635e-01,  2.66980175e-01,
         1.38940708e-01],
       [ 8.46117686e-01, -1.13177013e-01,  1.18587561e+00,
         1.32457142e+00],
       [ 7.25268265e-01, -6.22876257e-01,  1.07101368e+00,
         1.32457142e+00],
       [-3.62376523e-01, -1.38742512e+00,  1.52118246e-01,
         1.38940708e-01],
       [ 6.04418844e-01, -1.38742512e+00,  7.26427895e-01,
         9.29361182e-01],
       [ 2.29631074e+00, -1.13257550e+00,  1.81761623e+00,
         1.45630816e+00],
       [-2.41527102e-01, -1.13177013e-01,  4.39273070e-01,
         4.02414200e-01],
       [-1.20677681e-01,  3.45471769e+00, -1.28365588e+00,
        -1.04669000e+00],
       [-4.83225943e-01, -1.13177013e-01,  4.39273070e-01,
         4.02414200e-01],
       [-9.66623627e-01,  1.16107110e+00, -1.22622491e+00,
        -7.83216511e-01],
       [ 1.71740112e-04, -8.77725879e-01,  9.46872806e-02,
         7.20396281e-03],
       [ 8.46117686e-01, -6.22876257e-01,  4.96704035e-01,
         4.02414200e-01],
       [-9.66623627e-01,  9.06221475e-01, -1.22622491e+00,
        -1.04669000e+00],
       [ 2.41870582e-01, -3.68026635e-01,  4.39273070e-01,
         4.02414200e-01],
       [-1.20832247e+00, -1.13177013e-01, -1.34108684e+00,
        -1.17842675e+00],
       [-1.20832247e+00,  9.06221475e-01, -1.05393202e+00,
        -1.31016349e+00],
       [ 1.08781653e+00, -1.13177013e-01,  8.41289825e-01,
         1.45630816e+00],
       [ 1.71740112e-04, -6.22876257e-01,  7.83858860e-01,
         1.58804491e+00],
       [ 7.25268265e-01, -6.22876257e-01,  1.07101368e+00,
         1.19283467e+00],
       [ 7.25268265e-01,  3.96522231e-01,  4.39273070e-01,
         4.02414200e-01],
       [-8.45774206e-01,  1.67077034e+00, -1.28365588e+00,
        -1.04669000e+00],
       [ 6.04418844e-01, -1.38742512e+00,  6.68996930e-01,
         4.02414200e-01],
       [-1.45002131e+00,  1.41672609e-01, -1.28365588e+00,
        -1.31016349e+00],
       [ 1.32951537e+00,  1.41672609e-01,  7.83858860e-01,
         1.45630816e+00],
       [-1.20832247e+00,  1.41672609e-01, -1.22622491e+00,
        -1.31016349e+00],
       [ 8.46117686e-01, -1.13177013e-01,  8.41289825e-01,
         1.06109793e+00],
       [ 1.08781653e+00, -1.38742512e+00,  1.18587561e+00,
         7.97624436e-01],
       [-9.66623627e-01,  6.51371853e-01, -1.34108684e+00,
        -1.31016349e+00],
       [ 2.29631074e+00,  1.92561996e+00,  1.70275430e+00,
         1.32457142e+00],
       [-1.81256957e+00, -1.13177013e-01, -1.51337974e+00,
        -1.44190024e+00],
       [-3.62376523e-01, -1.13257550e+00,  3.81842105e-01,
         7.20396281e-03],
       [-1.69172015e+00, -3.68026635e-01, -1.34108684e+00,
        -1.31016349e+00],
       [ 2.41870582e-01, -8.77725879e-01,  7.83858860e-01,
         5.34150945e-01],
       [ 2.41870582e-01, -2.15197399e+00,  1.52118246e-01,
        -2.56269528e-01],
       [-8.45774206e-01,  1.16107110e+00, -1.34108684e+00,
        -1.31016349e+00],
       [-1.08747305e+00, -1.13177013e-01, -1.34108684e+00,
        -1.31016349e+00],
       [-7.24924785e-01, -8.77725879e-01,  9.46872806e-02,
         2.70677454e-01],
       [-1.45002131e+00,  1.41592072e+00, -1.57081070e+00,
        -1.31016349e+00],
       [ 3.62720003e-01, -3.68026635e-01,  5.54135000e-01,
         2.70677454e-01],
       [ 1.08781653e+00,  1.41672609e-01,  3.81842105e-01,
         2.70677454e-01],
       [-9.66623627e-01,  9.06221475e-01, -1.28365588e+00,
        -1.31016349e+00],
       [-2.41527102e-01, -1.13177013e-01,  2.09549210e-01,
         1.38940708e-01],
       [-8.45774206e-01, -1.38742512e+00, -4.22191404e-01,
        -1.24532783e-01],
       [ 1.21021161e-01,  3.96522231e-01,  6.11565965e-01,
         7.97624436e-01],
       [ 1.32951537e+00,  1.41672609e-01,  6.68996930e-01,
         4.02414200e-01],
       [ 6.04418844e-01, -3.68026635e-01,  1.07101368e+00,
         7.97624436e-01],
       [-4.83225943e-01,  9.06221475e-01, -1.16879395e+00,
        -1.31016349e+00],
       [-9.66623627e-01, -1.13177013e-01, -1.22622491e+00,
        -1.31016349e+00],
       [ 6.04418844e-01,  9.06221475e-01,  1.07101368e+00,
         1.58804491e+00],
       [ 3.62720003e-01, -6.22876257e-01,  5.54135000e-01,
         7.20396281e-03],
       [ 2.53800958e+00,  1.92561996e+00,  1.53046140e+00,
         1.06109793e+00],
       [-3.62376523e-01, -1.64227474e+00, -2.01746492e-02,
        -2.56269528e-01],
       [ 2.29631074e+00, -1.13177013e-01,  1.35816851e+00,
         1.45630816e+00],
       [ 1.32951537e+00,  1.41672609e-01,  9.56151755e-01,
         1.19283467e+00],
       [ 7.25268265e-01, -3.68026635e-01,  3.24411140e-01,
         1.38940708e-01],
       [ 1.20866595e+00,  3.96522231e-01,  1.24330658e+00,
         1.45630816e+00],
       [-8.45774206e-01,  9.06221475e-01, -1.28365588e+00,
        -1.31016349e+00],
       [-1.66084584e+00,  4.61630592e-01, -1.39118165e+00,
        -1.29333560e+00],
       [-7.99654122e-01,  1.16107110e+00, -1.31916931e+00,
        -1.22870179e+00],
       [-3.03912518e-01, -1.13177013e-01,  4.39273070e-01,
         4.02414200e-01],
       [-1.61119289e-01, -8.76723339e-01, -1.15817616e-01,
        -1.24014550e-01],
       [-2.48305046e-01, -9.06312804e-01,  2.60538044e-01,
         1.38940708e-01],
       [ 6.15905380e-01, -5.01507204e-01,  5.24054838e-01,
         3.39676166e-01]])

In [ ]:
x_test = sc.transform(x_test)
x_test

array([[ 1.71740112e-04, -8.77725879e-01,  7.83858860e-01,
         9.29361182e-01],
       [-1.20677681e-01, -1.13177013e-01,  2.66980175e-01,
         7.20396281e-03],
       [ 6.04418844e-01,  6.51371853e-01,  5.54135000e-01,
         5.34150945e-01],
       [ 2.17546132e+00, -1.13177013e-01,  1.64532333e+00,
         1.19283467e+00],
       [ 6.04418844e-01,  6.51371853e-01,  1.30073754e+00,
         1.71978166e+00],
       [ 1.08781653e+00, -1.13177013e-01,  7.26427895e-01,
         6.65887691e-01],
       [ 3.62720003e-01, -1.13177013e-01,  4.96704035e-01,
         2.70677454e-01],
       [-1.20677681e-01, -6.22876257e-01,  4.39273070e-01,
         1.38940708e-01],
       [-8.45774206e-01,  1.92561996e+00, -1.22622491e+00,
        -1.31016349e+00],
       [ 1.21021161e-01, -1.13177013e-01,  2.66980175e-01,
         4.02414200e-01],
       [-4.83225943e-01,  2.18046958e+00, -1.16879395e+00,
        -1.04669000e+00],
       [-4.83225943e-01,  2.18046958e+00, -1.39851781e+00,
        -1.04669000e+00],
       [-9.66623627e-01, -1.89712437e+00, -2.49898509e-01,
        -2.56269528e-01],
       [ 1.71740112e-04,  2.43531921e+00, -1.45594877e+00,
        -1.31016349e+00],
       [-9.66623627e-01, -2.66167323e+00, -1.35036579e-01,
        -2.56269528e-01],
       [-3.62376523e-01,  2.94501845e+00, -1.34108684e+00,
        -1.31016349e+00],
       [ 9.66967107e-01, -1.13177013e-01,  3.81842105e-01,
         2.70677454e-01],
       [-1.32917189e+00,  3.96522231e-01, -1.22622491e+00,
        -1.31016349e+00],
       [ 4.83569424e-01, -2.15197399e+00,  4.39273070e-01,
         4.02414200e-01],
       [-3.62376523e-01,  1.16107110e+00, -1.39851781e+00,
        -1.31016349e+00],
       [ 2.41870582e-01, -2.15197399e+00,  7.26427895e-01,
         4.02414200e-01],
       [ 1.08781653e+00,  1.41672609e-01,  5.54135000e-01,
         4.02414200e-01],
       [-4.83225943e-01,  9.06221475e-01, -1.28365588e+00,
        -1.04669000e+00],
       [ 1.93376247e+00, -6.22876257e-01,  1.35816851e+00,
         9.29361182e-01],
       [ 7.25268265e-01, -8.77725879e-01,  8.98720790e-01,
         9.29361182e-01],
       [-8.45774206e-01,  1.92561996e+00, -1.28365588e+00,
        -1.17842675e+00],
       [-3.62376523e-01, -1.89712437e+00,  1.52118246e-01,
         1.38940708e-01],
       [ 1.45036479e+00,  3.96522231e-01,  5.54135000e-01,
         2.70677454e-01],
       [ 2.29631074e+00, -6.22876257e-01,  1.70275430e+00,
         1.06109793e+00],
       [ 1.08781653e+00,  6.51371853e-01,  1.12844465e+00,
         1.71978166e+00]])

In [ ]:
# from sklearn.neighbors import KNeighborsClassifier

# knn = KNeighborsClassifier(n_neighbors=7)
# knn

In [ ]:
# knn.fit(x_train1,y_train1)

In [ ]:
# y_pred = knn.predict(x_test)
# y_pred

In [ ]:
from sklearn.svm import SVC

svm = SVC(C=1,kernel='poly')
svm

SVC(C=1, kernel='poly')

In [ ]:
svm.fit(x_train1,y_train1)

SVC(C=1, kernel='poly')

In [ ]:
y_pred = svm.predict(x_test)
y_pred

array(['Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica'],
      dtype=object)

In [ ]:
# performance evaluation
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
cm = confusion_matrix(y_test,y_pred)
print(cm)

accuracy = accuracy_score(y_test,y_pred)
print(accuracy)

cr = classification_report(y_test,y_pred)
print(cr)

[[ 9  0  0]
 [ 0 13  0]
 [ 0  0  8]]
1.0
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         9
Iris-versicolor       1.00      1.00      1.00        13
 Iris-virginica       1.00      1.00      1.00         8

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30